[build]
  publish = "."

# Reindirizzamento per l'API (Proxy verso Google Apps Script)
[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbw2qW3zlen0UJ4urE9HCHsD-bMxGSf9wiXoVzPTGuRMdGOwOV35JlWiWORfGNvRbRJP/exec"
  status = 200
  force = true

# Reindirizzamento per la Dashboard del Staff (Barbiere)
[[redirects]]
  from = "/admin"
  to = "/frontend-dashboard/admin.html"
  status = 200

# Reindirizzamento per tutte le altre rotte verso la SPA Clienti
[[redirects]]
  from = "/*"
  to = "/frontend-client/index.html"
  status = 200
